services:
  - type: web
    name: jodi-meds
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn simple_server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MEDS_CSV_PATH
        value: /opt/render/project/src/medications.csv
